# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cff941acd72989a221d0116a4fb3c2ee21e1d08282485158d61e778dd2acec921352cea0fbb40b6fd1d53e22cea1f6e7d6a1071dd97e5ae74d496795bcc66d03

test:
  secret_key_base: 94c0e0648b036500b9390316bbcedd7d420bf1afa27583d0ecabe74195a3517f2c6d49c7dfa5c8d6f57a9cdda43ee247f37bda1e65b880c6cca2a3cc055a6106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
